**Numpy**

In [ ]:
## numpy is used for scientific calculations

In [ ]:
import numpy as np

**One dimensional array**

In [ ]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a = []
size = int(input("enter size:"))
for i in range(size):
  val = int(input("enter number:"))
  a.append(val)

print(a)
b = np.array(a)
b

enter size:3
enter number:12
enter number:13
enter number:14
[12, 13, 14]


array([12, 13, 14])

**Two dimensional array**

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**How to check size and dimension of an array?**

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("total dimensions: " , b.ndim)
print("shape of an array: " , b.shape)    ##shape = n(rows), n(columns)
print("total elements: " , b.size)      ##size = row*column = total_element

total dimensions:  2
shape of an array:  (3, 3)
total elements:  9


**Numpy Funtions**

In [ ]:
## 1. Zeros ===> this function create an array (either one dimensional or multi dimensional) and fill all the values with zeroes

In [ ]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
a.ndim

1

In [ ]:
## 2. Ones ===> this function create an array (either one dimensional or multi dimensional) and fill all the values with one.

In [ ]:
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
## eye ===> This function creates an array with all the diagonal elements as 1 and rest are 0 (in square matrix).
##In non-square matrix the value are still one for diagonal (upto which it can draw diagonal) and rest are zero.

In [ ]:
import numpy as np
a = np.eye(3)    ## n(rows) = n(columns) ==> symmetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b = np.eye(3,4)     ## n(rows) != n(columns) ==> Asymmetric matrix
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4. diag ===> this function creates a two dimensional array with all the diagonal elements as the given value and rest are zero

In [ ]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [ ]:
# 5. randint ==> this function is used to generate a random number between a given range.

#syntax == randint(min_value , max_value , total_numbers)

In [ ]:
import numpy as np
a = np.random.randint(1,10,3)
a

array([8, 3, 5])

In [ ]:
# 6. rand() ==> this function is used to generate a random number between 0 to 1.

#syntax == rand(number of values)

In [ ]:
import numpy as np

a = np.random.rand(5)
a

array([0.5088324 , 0.64735011, 0.32761376, 0.23095024, 0.53373371])

In [ ]:
# 7. randn() ==> this function is used to generate a random number from -3 to close 3. This may return positive or negative numbers as well.

#syntax == random.randn(number of values)

In [ ]:
import numpy as np
a = np.random.randn(5)
a

array([-2.38212763,  0.3347127 ,  0.46125456,  1.02498314,  0.31553496])

**Reshaping Data**

In [ ]:
# n(rows) * n(columns) = n(total_elements) ===> condition always true.

In [ ]:
import numpy as np
a = np.random.randint(1,50,12)
a

array([ 6, 25, 35, 19, 23, 29, 16,  1,  8,  8, 29, 31])

In [ ]:
# n(rows) * n(columns) = n(total_elements)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(2,6)
#a

array([[ 6, 25, 35, 19, 23, 29],
       [16,  1,  8,  8, 29, 31]])

In [ ]:
a.reshape(6,2)
#a

array([[ 6, 25],
       [35, 19],
       [23, 29],
       [16,  1],
       [ 8,  8],
       [29, 31]])

In [ ]:
a.reshape(3,4)
#a

array([[ 6, 25, 35, 19],
       [23, 29, 16,  1],
       [ 8,  8, 29, 31]])

**Seed Function() ===> we know that randint function generates random numbers. Everytime we run the program , new set of random number is generated. So, solve this problem we will use seed function.**

In [ ]:
import numpy as np

np.random.seed(50)
a = np.random.randint(1,100,10)
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6])

**View VS Copy ==> when we slice a sub-array from an array, it may done by two ways.**

**View is used to do modifications in the original data.**


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

**Copy**

In [ ]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b

array([0, 0, 0])

**Conditional Selection** **==**
**starting value included and last value excluded**

In [ ]:
import numpy as np
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [94]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [93]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b  = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
b-a

array([[4, 4],
       [4, 4]])

In [ ]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)   ####for matrix multiplication

array([[19, 22],
       [43, 50]])

***np.unique(arr , return_index = True , return_counts = True) ***

returns 3 array
1. the array with unique values.
2. the array with respective index value.
3. the array with counting of frequency.

In [ ]:
a = np.array([10,20,30,40,10,20,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 6]), array([2, 2, 1, 1, 1]))

**Horizontal and Vertical Stacking**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
a

array([1, 2, 3, 4])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Questions for today**

In [ ]:
# Q.1 = Write statement to import numpy?

import numpy as np

In [ ]:
# Q.2 Create an array using numpy?

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
# Q.3 Create an array of 10 random integers?

a = np.random.randint(1,50,10)
a

array([ 3, 32,  8, 48,  5, 15, 36, 29, 28, 27])

In [ ]:
# Q.4 Create an array of elements from 10-20?

a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# Q.5 Create an array which contains value 5, 10 times?

a = np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Q.6 Create a one dimensional array and convert that into 3*3 matrix ?

a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Q.7 Create a 2D array of size 3'3 but all the elements should be between 0 to 1?

a = np.random.rand(3,3)
a

array([[0.14546686, 0.97266468, 0.90917844],
       [0.5599571 , 0.31359075, 0.88820004],
       [0.67457307, 0.39108745, 0.50718412]])

In [ ]:
# Q.8 Concatenate 2D array horizontally and vertically?


a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack((a))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.vstack((a))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])